### ISSUE TITLE
Should this work with webpack instead of system.js

### ISSUE THREAD

**Issue by ronnyek** [ng-lightning/ng-lightning#257]
So I've only recently become aware of ng-lightning and trying to consume it in an already built ng2 app that uses webpack. I added ng-lightning/ng-lightning to my webpack.config for inclusion into my vendor stuff, but as soon as it starts getting called, it blows up. I cant tell from this if the problem is in ng-lightning or not. 

```
Exception: Call to Node module failed with error: C:\source\IssueTrackerWeb\node_modules\ng-lightning\ng-lightning.js:1
(function (exports, require, module, __filename, __dirname) { import { NgModule } from '@angular/core';
^^^^^^
SyntaxError: Unexpected token import
at Object.exports.runInThisContext (vm.js:76:16)
at Module._compile (module.js:542:28)
at Object.Module._extensions..js (module.js:579:10)
at Module.load (module.js:487:32)
at tryModuleLoad (module.js:446:12)
at Function.Module._load (module.js:438:3)
at Module.require (module.js:497:17)
at require (internal/module.js:20:19)
at Object.<anonymous> (C:\source\IssueTrackerWeb\ClientApp\dist\main-server.js:535:19)
at __webpack_require__ (C:\source\IssueTrackerWeb\ClientApp\dist\main-server.js:20:30)
```

**Comment by bekos** [comment]
@ronnyek I suppose you use Webpack v1, but because we lately ship ES modules (for tree shaking) you could either upgrade to Webpack v2 or use our UMD bundle. 

If you think this something we can do on our side, please feel free to reopen.
