### ISSUE TITLE
Error Installing ng-lightning  | Tether dependency error

### ISSUE THREAD

**Issue by mayordwells** [ng-lightning/ng-lightning#291]
GET http://localhost:3000/tether 404 (Not Found)
scheduleTask @ zone.js:1561
ZoneDelegate.scheduleTask @ zone.js:242
Zone.scheduleMacroTask @ zone.js:168
(anonymous) @ zone.js:1584
send @ VM7051:3
fetchTextFromURL @ system.src.js:1051
(anonymous) @ system.src.js:1778
ZoneAwarePromise @ zone.js:525
(anonymous) @ system.src.js:1777
(anonymous) @ system.src.js:2806
(anonymous) @ system.src.js:3384
(anonymous) @ system.src.js:3707
(anonymous) @ system.src.js:4099
(anonymous) @ system.src.js:4562
(anonymous) @ system.src.js:4831
(anonymous) @ system.src.js:407
ZoneDelegate.invoke @ zone.js:229
Zone.run @ zone.js:113
(anonymous) @ zone.js:509
ZoneDelegate.invokeTask @ zone.js:262
Zone.runTask @ zone.js:151
drainMicroTaskQueue @ zone.js:405
ZoneTask.invoke @ zone.js:336
projects:41 Error: (SystemJS) XHR error (404 Not Found) loading http://localhost:3000/tether
	Error: XHR error (404 Not Found) loading http://localhost:3000/tether
	    at XMLHttpRequest.wrapFn [as _onreadystatechange] (http://localhost:3000/node_modules/zone.js/dist/zone.js:851:29) [<root>]
	    at Zone.runTask (http://localhost:3000/node_modules/zone.js/dist/zone.js:151:47) [<root> => <root>]
	    at XMLHttpRequest.ZoneTask.invoke (http://localhost:3000/node_modules/zone.js/dist/zone.js:332:33) [<root>]
	Error loading http://localhost:3000/tether as "tether" from https://unpkg.com/ng-lightning@1.2.0/bundles/ng-lightning.umd.js
	    at XMLHttpRequest.wrapFn [as _onreadystatechange] (http://localhost:3000/node_modules/zone.js/dist/zone.js:851:29) [<root>]
	    at Zone.runTask (http://localhost:3000/node_modules/zone.js/dist/zone.js:151:47) [<root> => <root>]
	    at XMLHttpRequest.ZoneTask.invoke (http://localhost:3000/node_modules/zone.js/dist/zone.js:332:33) [<root>]
	Error loading http://localhost:3000/tether as "tether" from https://unpkg.com/ng-lightning@1.2.0/bundles/ng-lightning.umd.js

I have followed the instruction on getting started page and i got the following error when i tried to use this package, it creates a dependency error that ceases my app from loading until i disable it, 
I have tether installed in node_modules and i have even have it imported from CDN but still no solution. Any idea on how to fix this please?

**Comment by mayordwells** [comment]
was able to fix it by adding the location of tether to the paths obj in systemjs.config.js

paths: {
      // paths serve as alias
      'npm:': 'node_modules/',
      'tether': 'node_modules/tether/dist/js/tether.min.js'
      //'tether': 'https://cdnjs.cloudflare.com/ajax/libs/tether/1.3.1/js/tether.min.js',
    },
