### ISSUE TITLE
Datatable error when there is no data for the second time

### ISSUE THREAD

**Issue by eheck** [ng-lightning/ng-lightning#317]
We have a search form that hits an API and shows the result in a ngl-datatable.
When we run two consecutive search with no data, the page crashes.
We are using the version 1.2.0 of lightning. This is the stacktrace:

"Error: Error in ./NglDatatable class NglDatatable - inline template:1:390 caused by: Cannot read property 'type' of undefined
    at ViewWrappedError.k (http://127.0.0.1/node_modules/zone.js/dist/zone.min.js:1:12455)
    at ViewWrappedError.BaseError [as constructor] (http://127.0.0.1/node_modules/@angular/core/bundles/core.umd.js:1239:20)
    at ViewWrappedError.WrappedError [as constructor] (http://127.0.0.1/node_modules/@angular/core/bundles/core.umd.js:1297:20)
    at new ViewWrappedError (http://127.0.0.1/node_modules/@angular/core/bundles/core.umd.js:6167:20)
    at View_NglDatatable2.DebugAppView._rethrowWithContext (http://127.0.0.1/node_modules/@angular/core/bundles/core.umd.js:12385:27)
    at View_NglDatatable2.DebugAppView.detectChanges (http://127.0.0.1/node_modules/@angular/core/bundles/core.umd.js:12358:22)
    at ViewContainer.detectChangesInNestedViews (http://127.0.0.1/node_modules/@angular/core/bundles/core.umd.js:12466:41)
    at CompiledTemplate.proxyViewClass.View_NglDatatable0.detectChangesInternal (/NglDatatablesModule/NglDatatable/component.ngfactory.js:500:14)
    at CompiledTemplate.proxyViewClass.AppView.detectChanges (http://127.0.0.1/node_modules/@angular/core/bundles/core.umd.js:12208:18)
    at CompiledTemplate.proxyViewClass.DebugAppView.detectChanges (http://127.0.0.1/node_modules/@angular/core/bundles/core.umd.js:12355:48)
    at CompiledTemplate.proxyViewClass.AppView.internalDetectChanges (http://127.0.0.1/node_modules/@angular/core/bundles/core.umd.js:12193:22)
    at View_ClientListComponent33.detectChangesInternal (/FBAppModule/ClientListComponent/component.ngfactory.js:5802:20)
    at View_ClientListComponent33.AppView.detectChanges (http://127.0.0.1/node_modules/@angular/core/bundles/core.umd.js:12208:18)
    at View_ClientListComponent33.DebugAppView.detectChanges (http://127.0.0.1/node_modules/@angular/core/bundles/core.umd.js:12355:48)
    at ViewContainer.detectChangesInNestedViews (http://127.0.0.1/node_modules/@angular/core/bundles/core.umd.js:12466:41)"

**Comment by bekos** [comment]
@eheck Datatable should be stateless, so it doesn't matter if it is the first or second time you pass no data to the component. Can you provide a reproduce scenario using our plunker? Otherwise it would be very difficult for me to understand what is the real problem.

**Comment by eheck** [comment]
@bekos Thanks for the reply.
We find our problem: we had <template *ngIf="!loading" nglNoRowsOverlay>No Tasks</template> in our datatable component. The ngIf causes the exception when loading was true.

**Comment by bekos** [comment]
@eheck Glad you found it 👍
