### ISSUE TITLE
Installation error caused by typings

### ISSUE THREAD

**Issue by deastr** [ng-lightning/ng-lightning#81]
I'm trying to install ng-lightning to an ASP.MVC 5 project using Visual Studio.NET 2015 and packages.config and I'm getting this error on installation:

```
====Executing command 'npm install'====

npm http GET https://registry.npmjs.org/ng-lightning
npm http 304 https://registry.npmjs.org/ng-lightning
> ng-lightning@0.7.0 postinstall D:\Projects\xxx\Source\Management\Management.Web.UI\node_modules\ng-lightning
> typings install
typings ERR! message Unable to resolve Typings dependencies
npm ERR! ng-lightning@0.7.0 postinstall: `typings install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ng-lightning@0.7.0 postinstall script.
npm ERR! This is most likely a problem with the ng-lightning package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     typings install
npm ERR! You can get their info via:
npm ERR!     npm owner ls ng-lightning
npm ERR! There is likely additional logging output above.
npm ERR! System Windows_NT 6.2.9200
npm ERR! command "C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\Common7\\IDE\\Extensions\\Microsoft\\Web Tools\\External\\\\node\\node" "C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\Common7\\IDE\\Extensions\\Microsoft\\Web Tools\\External\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! cwd D:\Projects\xxx\Source\Management\Management.Web.UI
npm ERR! node -v v0.10.31
npm ERR! npm -v 1.4.9
npm ERR! code ELIFECYCLE
npm

====npm command completed with exit code 1====
```

My packages.config file:

```
{
    "version": "1.0.0",
    "name": "ASP.NET",
    "private": true,
    "dependencies": {
        "angular2": "2.0.0-beta.15",
        "systemjs": "0.19.26",
        "es6-promise": "^3.1.2",
        "es6-shim": "^0.35.0",
        "reflect-metadata": "0.1.2",
        "rxjs": "5.0.0-beta.2",
        "zone.js": "0.6.10",
        "bootstrap": "^3.3.6",
        "jquery": "^2.2.3",
        "underscore": "1.8.3",
        "fontawesome": "4.5.0",
        "bootstrap-material-design": "^0.5.9",
        "typings": "0.8.1",
        "ng-lightning": "0.7.0"
    },
    "devDependencies": {
        "gulp": "3.9.1",
        "gulp-clean": "0.3.2",
        "gulp-concat": "2.6.0",
        "gulp-continuous-concat": "0.1.1",
        "gulp-watch": "4.3.5"
    }
}
```

Any ideas?

**Comment by ppolyzos** [comment]
To overcome this issue please install `typings` globally before installing `ng-lightning`.
`npm install -g typings` and then
`npm install --save ng-lightning`

**Comment by deastr** [comment]
I started "Node.js command prompt" from Start menu and executed "npm install -g typings". The package got installed to "c:\Users\deastr\AppData\Roaming\npm\node_modules\typings" folder. I tried to install ng-lightning again but got same error. 

I copied that folder to "<project>\node_modules\typings" folder and tried again but again got the same error.

Is this happening because I don't use node.js in my project?

**Comment by ppolyzos** [comment]
There is no need to copy `typings` folder in your node_modules folder. 
Please make sure that `typings` is properly installed in your system, by typing:
`typings -version`.

If this still doesn't work, try to remove `typings` dependency from your `package.json` file and reinstall `ng-lightning`

**Comment by deastr** [comment]
I deleted node_modules\typings folder. typings -version displays 0.8.1 in cmdline. I tried to install again using packages.json and got this error:

```
====Executing command 'npm install'====


npm http GET https://registry.npmjs.org/ng-lightning
npm http 304 https://registry.npmjs.org/ng-lightning
> ng-lightning@0.7.0 postinstall D:\Projects\KYSV3\Source\Management\Management.Web.UI\node_modules\ng-lightning
> typings install
module.js:340
    throw err;
          ^
Error: Cannot find module 'D:\Projects\KYSV3\Source\Management\Management.Web.UI\node_modules\typings\dist\bin.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
npm ERR! ng-lightning@0.7.0 postinstall: `typings install`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the ng-lightning@0.7.0 postinstall script.
npm ERR! This is most likely a problem with the ng-lightning package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     typings install
npm ERR! You can get their info via:
npm ERR!     npm owner ls ng-lightning
npm ERR! There is likely additional logging output above.
npm ERR! System Windows_NT 6.2.9200
npm ERR! command "C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\Common7\\IDE\\Extensions\\Microsoft\\Web Tools\\External\\\\node\\node" "C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\Common7\\IDE\\Extensions\\Microsoft\\Web Tools\\External\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! cwd D:\Projects\KYSV3\Source\Management\Management.Web.UI
npm ERR! node -v v0.10.31
npm ERR! npm -v 1.4.9
npm ERR! code ELIFECYCLE
npm

====npm command completed with exit code 1====
```

**Comment by bekos** [comment]
@deastr Can you try to delete all your `node_modules` and try `npm install` again now that typings is globally installed?

**Comment by deastr** [comment]
I ran npm install on my solution root folder where my packages.json is. It installed everything on the packages.json file but not typings. Typings is not a dependency in the packages.json file. Do you want me to install typings again using packages.json?

**Comment by bekos** [comment]
@deastr Closing as I don't see any way we can help here. If you find anything specific we can improve on our side, please feel free to reopen this.

**Comment by sadesyllas** [comment]
@deastr, I also work with windows a lot and every time I have come across this issue the solution has been to simply re-run the `npm install

**Comment by bekos** [comment]
@deastr I now realize that your issue may be related to #90. I will try to fix this soon.
